import { useState, useEffect } from "react";
import { toast } from "react-toastify";
import { ClipboardIcon, PlusIcon } from "@heroicons/react/24/outline";
import GenerateApiKeyModal from "./model/GenerateApiKeyModal";

const ApiKeyManagement = () => {
  const [apiKeys, setApiKeys] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const API_URL = "https://admin-admin-credit.onrender.com/api";
  const token = localStorage.getItem("adminToken");

  // Fetch API Keys
  useEffect(() => {
    fetchApiKeys();
  }, []);

  const fetchApiKeys = async () => {
    try {
      setLoading(true);
      const res = await fetch(`${API_URL}/admin/api-keys`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.success) {
        setApiKeys(data.apiKeys || []);
      } else {
        toast.error(data.message || "Failed to fetch API keys");
      }
    } catch (err) {
      console.error("Fetch API keys error:", err);
      toast.error("Error connecting to server");
    } finally {
      setLoading(false);
    }
  };

  const generateApiKey = async ({ name, expiry }) => {
    try {
      setGenerating(true);
      const res = await fetch(`${API_URL}/admin/api-keys/generate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ name, expiry: expiry || null }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success("API key generated successfully");
        fetchApiKeys(); // Refresh the list
        setShowModal(false);
      } else {
        toast.error(data.message || "Failed to generate API key");
      }
    } catch (err) {
      console.error("Generate API key error:", err);
      toast.error("Error connecting to server");
    } finally {
      setGenerating(false);
    }
  };

  const revokeKey = async (id) => {
    if (!window.confirm("Are you sure you want to revoke this API key?"))
      return;

    try {
      const res = await fetch(`${API_URL}/admin/api-keys/${id}/revoke`, {
        method: "PUT",
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.success) {
        toast.success("API key revoked successfully");
        fetchApiKeys(); // Refresh the list
      } else {
        toast.error(data.message || "Failed to revoke API key");
      }
    } catch (err) {
      console.error("Revoke API key error:", err);
      toast.error("Error connecting to server");
    }
  };

  if (loading) {
    return (
      <div className="max-w-5xl mx-auto p-4 md:p-6 flex items-center justify-center">
        <div className="text-gray-600">Loading API keys...</div>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto p-4 md:p-6">
      {/* Header */}
      <div className="mb-4 flex items-center justify-between">
        <h2 className="text-lg font-semibold text-gray-900">
          API Key Management
        </h2>
        <button
          onClick={() => setShowModal(true)}
          className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
        >
          <PlusIcon className="h-4 w-4" />
          Generate New API Key
        </button>
      </div>

      {/* Table */}
      <div className="overflow-x-auto rounded-lg border border-gray-200 bg-white">
        <table className="w-full text-left text-sm">
          <thead className="bg-gray-50 text-gray-600">
            <tr>
              <th className="px-4 py-3 font-medium">API Key</th>
              <th className="px-4 py-3 font-medium">Generated By</th>
              <th className="px-4 py-3 font-medium">Last Used</th>
              <th className="px-4 py-3 font-medium">Expiry Date</th>
              <th className="px-4 py-3 font-medium">Status</th>
              <th className="px-4 py-3 font-medium">Actions</th>
            </tr>
          </thead>

          <tbody className="divide-y divide-gray-100">
            {apiKeys.length === 0 ? (
              <tr>
                <td colSpan="6" className="px-4 py-8 text-center text-gray-500">
                  No API keys found
                </td>
              </tr>
            ) : (
              apiKeys.map((key) => (
                <tr key={key._id}>
                  <td className="px-4 py-3 flex items-center gap-2 font-medium text-gray-900">
                    {key.key}
                    <ClipboardIcon className="h-4 w-4 text-gray-400 cursor-pointer" />
                  </td>
                  <td className="px-4 py-3">{key.generatedBy}</td>
                  <td className="px-4 py-3">{key.lastUsed || "—"}</td>
                  <td className="px-4 py-3">{key.expiry || "—"}</td>
                  <td className="px-4 py-3">
                    <span
                      className={`rounded-full px-3 py-1 text-xs font-medium ${
                        key.status === "Active"
                          ? "bg-green-100 text-green-700"
                          : "bg-red-100 text-red-700"
                      }`}
                    >
                      {key.status}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    {key.status === "Active" && (
                      <button
                        onClick={() => revokeKey(key._id)}
                        className="rounded-md bg-red-50 px-3 py-1 text-xs font-medium text-red-600 hover:bg-red-100"
                      >
                        Revoke
                      </button>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Modal */}
      {showModal && (
        <GenerateApiKeyModal
          onClose={() => setShowModal(false)}
          onGenerate={generateApiKey}
          loading={generating}
        />
      )}
    </div>
  );
};

export default ApiKeyManagement;
